# --------------------------- #
#
# Tutorial: 
# Admixture > Pie charts > Map
#
# Description:
# Tutorial on how to run STRUCTURE-like analyses in R, plot admixture proportions
# using pie charts, and visualise the pie charts on a map.
# 
# Data:
# European lobster SNP genotypes generated by a Fluidigm EP1 system.
# Tutorial uses ten sites from the original study (Jenkins et al. 2019).
# Data can be download from the link below:
# https://doi.org/10.5061/dryad.2v1kr38
# "lobster_1278ind_79snps_40pop.RData" in Miscellaneous_files.zip
#
# Notes before execution:
# 1. Make sure all required R packages are installed.
# 2. Set your working directory to the location of this R script.
#
# --------------------------- #

# Load packages
library(adegenet)
library(poppr)
library(LEA)
library(reshape2)
library(dplyr)
library(ggplot2)
library(rworldmap)
library(rworldxtra)
library(ggsn)
library(sf)
library(raster)
library(rgeos)
library(maps)
library(maptools)
library(grid)
library(miscTools)
library(stringr)
library(ggpubr)

# Import genotypes
load("lobster_1278ind_79snps_40pop.RData")

# Explore data
data_filt
nLoc(data_filt) # number of loci
nPop(data_filt) # number of sites
nInd(data_filt) # number of individuals
summary(data_filt$pop) # sample size

# Subset data to reduce computation time
subsites = sort(c("Vig","Ios","Mul","Cro","She","Idr17","Hel","Flo","Lys","Ber"))
data_filt = popsub(data_filt, sublist = subsites)
data_filt


# ----------------- #
#
# Admixture analysis using SNMF from LEA
#
# ----------------- #

# Export genotypes in STRUCTURE format
source("TJ_genind2structure_function.R")
genind2structure(data_filt, file = "genotypes", pops = FALSE, markers = FALSE)

# Convert STRUCTURE file to .geno format
struct2geno("genotypes", ploidy = 2, FORMAT = 2, extra.column = 1)

# Run snmf algorithm
set.seed(123)
snmf1 = snmf("genotypes.geno",
             K = 1:10, # number of K ancestral populations to run
             repetitions = 10, # ten repetitions for each K
             entropy = TRUE, # calculate cross-entropy
             project = "new")

# Load snmf project
snmf1 = load.snmfProject("genotypes.snmfProject")

# Plot cross-entropy results to assess optimal number of K
# Smaller values of cross-entropy usually mean better runs
# A plateau usually represents the K that best fits the data
plot(snmf1, col = "blue", cex = 1.5, pch = 19)

# Extract the cross-entropy of all runs where K = 2
ce = cross.entropy(snmf1, K = 2)
ce

# Find the run with the lowest cross-entropy
lowest.ce = which.min(ce)
lowest.ce

# Extract Q-matrix for the best run
qmatrix = as.data.frame(Q(snmf1, K = 2, run = lowest.ce))
head(qmatrix)

# Label column names of qmatrix
ncol(qmatrix)
cluster_names = c()
for (i in 1:ncol(qmatrix)){
  cluster_names[i] = paste("Cluster", i)
}
cluster_names
colnames(qmatrix) = cluster_names
head(qmatrix)

# Add individual IDs
qmatrix$Ind = indNames(data_filt)

# Add site IDs
qmatrix$Site = data_filt$pop
head(qmatrix)

# Convert dataframe to long format
qlong = melt(qmatrix, id.vars=c("Ind","Site"))
head(qlong)

# Change order of sites by using the factor function
# site.order = c("Vig","Ios","Cor","Mul","She","Cro","Hel","Flo","Lys","Ber")
# qlong$Site_ord = factor(qlong$Site, levels = site.order)

# Adjust facet labels
levels(qlong$Site)
facet.labs = c("Bergen","Cromer","Flodevigen","Helgoland","Île de Ré",
               "Isles of Scilly","Lysekil","Mullet Peninsula","Shetland","Vigo")
levels(qlong$Site) = facet.labs
levels(qlong$Site)

# Define colour palette
pal = colorRampPalette(c("green","blue"))
cols = pal(length(unique(qlong$variable)))

# Plot admixture barplot 
admix.bar = ggplot(data=qlong, aes(x=Ind, y=value, fill=variable))+
  geom_bar(stat = "identity")+
  scale_y_continuous(expand = c(0,0))+
  facet_wrap(~Site, scales = "free", ncol = 2)+
  scale_fill_manual(values = cols)+
  ylab("Admixture proportion")+
  # xlab("Individual")+
  theme(axis.text.x = element_blank(),
        axis.ticks.x = element_blank(),
        axis.title.x = element_blank(),
        strip.text = element_text(colour="black", size=12),
        panel.grid = element_blank(),
        panel.background = element_blank(),
        legend.position = "top",
        legend.title = element_blank(),
        legend.text = element_text(size = 12))
admix.bar
ggsave("1.admixture_barplot.png", width=6, height=10, dpi=300)


# ----------------- #
#
# Prepare pie charts
#
# ----------------- #

# Calculate mean admixture proportions for each site
head(qmatrix)
clusters = grep("Cluster", names(qmatrix)) # indexes of cluster columns
avg_admix = aggregate(qmatrix[, clusters], list(qmatrix$Site), mean)

# Order alphabetically by site
avg_admix = avg_admix[order(as.character(avg_admix$Group.1)), ]
avg_admix

# Convert dataframe from wide to long format
avg_admix = melt(avg_admix, id.vars = "Group.1")
head(avg_admix)

# Define a function to plot pie charts using ggplot for each site
pie_charts = function(admix_df, site, cols){
  # admix_df = dataframe in long format of admixture proportions per site 
  # site = string 
  # cols = vector of colours of length(clusters)
  ggplot(data = subset(admix_df, Group.1 == site),
         aes(x = "", y = value, fill = variable))+
    geom_bar(width = 1, stat = "identity", colour = "black", show.legend = FALSE)+
    coord_polar(theta = "y")+
    scale_fill_manual(values = cols)+
    theme_void()
}

# Test function on one site
pie_charts(avg_admix, site = "Ber", cols = cols)

# Apply function to all sites using for loop
pies = list()
for (i in subsites){
  pies[[i]] = pie_charts(admix_df = avg_admix, site = i, cols = cols) 
}


# ----------------- #
#
# Prepare basemap
#
# ----------------- #

# Import csv file containing coordinates
coords = read.csv("coordinates.csv")

# Subset coordinates
coords = coords[coords$Code %in% subsites, ]

# Order alphabetically by site
coords = coords[order(coords$Code), ] 
coords

# Check order matches coords order
as.character(avg_admix$Group.1) == as.character(coords$Code)

# Set map boundary (xmin, xmax, ymin, ymax)
boundary = extent(-15, 15, 40, 64)
boundary

# Get map outlines from rworldmap package
map.outline = getMap(resolution = "high")

# Crop to boundary and convert to dataframe
map.outline = crop(map.outline, y = boundary) %>% fortify()

# Plot basemap
basemap = ggplot()+
  geom_polygon(data=map.outline, aes(x=long, y=lat, group=group), fill="grey",
               colour="black", size=0.5)+
  coord_quickmap(expand=F)+
  ggsn::north(map.outline, symbol = 10, scale = 0.06, location = "topleft")+
  ggsn::scalebar(data = map.outline, dist = 200, dist_unit = "km", height = 0.01,
                 transform = TRUE, model = "WGS84", 
                 location = "bottomleft", anchor = c(x = -12.5, y = 45),
                 st.bottom = FALSE, st.size = 4, st.dist = 0.015)+
  xlab("Longitude")+
  ylab("Latitude")+
  theme(
    axis.text = element_text(colour="black", size=12),
    axis.title = element_text(colour="black", size=14),
    panel.background = element_rect(fill="lightsteelblue2"),
    panel.border = element_rect(fill = NA, colour = "black", size = 0.5),
    panel.grid.minor = element_line(colour="grey90", size=0.5),
    panel.grid.major = element_line(colour="grey90", size=0.5),
    legend.text = element_text(size=12),
    legend.title = element_blank(),
    legend.key.size = unit(0.7, "cm"),
    legend.position = "top"
  )
basemap


# ----------------- #
#
# Add pie charts to basemap
#
# ----------------- #

# Extract coordinates for each site
coord.list = list()
for (i in subsites){
  coord.list[[i]] = c(subset(coords, Code == i)$Lon, subset(coords, Code == i)$Lat)
}
coord.list

# Define pie chart sizes
radius = 1

# Convert ggplot pie charts to annotation_custom layers
pies.ac = list()
for (i in 1:length(subsites)){
  pies.ac[[i]] = annotation_custom(grob = ggplotGrob(pies[[i]]),
                                   xmin = coord.list[[i]][[1]] - radius,
                                   xmax = coord.list[[i]][[1]] + radius,
                                   ymin = coord.list[[i]][[2]] - radius,
                                   ymax = coord.list[[i]][[2]] + radius)
}

# Add layers to basemap
pie.map = basemap + pies.ac
pie.map
ggsave("2.pie_charts_map.png", width = 8, height = 10, dpi = 300)

# Combine ggplots
ggarrange(admix.bar + theme(legend.position = "right") + labs(title = "Individual admixture proportions", tag = "A"),
          pie.map + labs(title = "Mean admixture proportions for each site", tag = "B"))
ggsave("3.Admixture_bar_map.png", width = 15, height = 10, dpi = 300)
